[[redirects]]
  from = "/docs/SDK/accessControlConditionExamples"
  to = "/docs/AccessControlConditions/evmBasicExamples"
  status = 302
  force = false

[[redirects]]
  from = "/docs/accessControlModal"
  to = "docs/ToolsAndExamples/shareModal"
  status = 302
  force = true

[[redirects]]
  from = "/docs/LitTools/shareModal"
  to = "/docs/ToolsAndExamples/shareModal"
  status = 302
  force = true

[[redirects]]
  from = "/docs/jwtVerifier"
  to = "/docs/ToolsAndExamples/additionalIntegrations#js-jwt-verifier"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/jwtVerifier"
  to = "/docs/ToolsAndExamples/additionalIntegrations#js-jwt-verifier"
  status = 302
  force = false

[[redirects]]
  from = "/docs/examples"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/examples"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/oauth"
  to = "/docs/ToolsAndExamples/additionalIntegrations#oauth-integrations"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/oauth"
  to = "/docs/ToolsAndExamples/additionalIntegrations#oauth-integrations"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ceramicIntegration"
  to = "/docs/ToolsAndExamples/Ceramic/intro"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/ceramicIntegration"
  to = "/docs/ToolsAndExamples/Ceramic/intro"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/intro"
  to = "/docs/SDK/intro"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/installation"
  to = "/docs/SDK/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/staticContent"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/SDKExamples/EncryptAndDecrypt/installation"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/dynamicContent"
  to = "/docs/ToolsAndExamples/SDKExamples/dynamicContent"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/SDKExamples/dynamicContent"
  to = "/docs/ToolsAndExamples/SDKExamples/dynamicContent"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/authSig"
  to = "/docs/SDK/authSig"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/errorHandling"
  to = "/docs/SDK/errorHandling"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/tests"
  to = "/docs/SDK/tests"
  status = 302
  force = false
  
[[redirects]]
from = "/docs/ExamplesAndGuides/examples"
to = "/docs/ExamplesAndGuides/SDKExamples/examples"
status = 302
force = false

[[redirects]]
  from = "/docs/whatislit/whatislitprotocol/"
  to = "/"
  status = 302
  force = false

[[redirects]]
  from = "/docs/WhatIsLit/howItWorks"
  to = "/docs/Introduction/howItWorks"
  status = 302
  force = false

[[redirects]]
  from = "/docs/intro"
  to = "/whatIsLit"
  status = 302
  force = false

[[redirects]]
  from = "/docs/AccessControlConditions/evmBasicExamples"
  to = "/docs/AccessControlConditions/EVM/basicExamples"
  status = 302
  force = false

[[redirects]]
  from = "/docs/AccessControlConditions/evmCustomContractCalls"
  to = "/docs/AccessControlConditions/EVM/customContractCalls"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/Ceramic/installation"
  to = "/docs/ToolsAndExamples/Ceramic/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/Ceramic/encryption"
  to = "/docs/ToolsAndExamples/Ceramic/encryption"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/Ceramic/decryption"
  to = "/docs/ToolsAndExamples/Ceramic/decryption"
  status = 302
  force = false

  [[redirects]]
  from = "/docs/ExamplesAndGuides/bundlrxarweave"
  to = "/docs/ToolsAndExamples/bundlrxarweave"
  status = 302
  force = false

# 7/21/22 - dating for deprecation purposes

[[redirects]]
  from = "/docs/Introduction/whatIsLitProtocol"
  to = "/"
  status = 302
  force = false

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 302
  force = false

# 10/18/22 - docs re-org 1.5

[[redirects]]
  from = "/LitActionsAndPKPs/whatAreLitActionsAndPKPs"
  to = "/coreConcepts/LitActionsAndPKPs/intro"
  status = 302
  force = false

[[redirects]]
  from = "/LitActionsAndPKPs/workingWithLitActions"
  to = "/coreConcepts/LitActionsAndPKPs/workingWithLitActions"
  status = 302
  force = false

[[redirects]]
  from = "/LitActionsAndPKPs/ToolsAndExamples"
  to = "/coreConcepts/LitActionsAndPKPs/ToolsAndExamples"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/installation"
  to = "/SDK/Explanation/installation"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/authSig"
  to = "/SDK/Explanation/authSig"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/sessionKeys"
  to = "/SDK/Explanation/authSig"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/errorHandling"
  to = "/SDK/Explanation/tests"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/tests"
  to = "/SDK/Explanation/tests"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/intro"
  to = "/coreConcepts/accessControl/intro"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/EVM/basicExamples"
  to = "/coreConcepts/accessControl/EVM/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/EVM/*"
  to = "/coreConcepts/accessControl/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/solRpcConditions"
  to = "/coreConcepts/accessControl/otherChains/solRpcConditions"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/cosmosConditions"
  to = "/coreConcepts/accessControl/otherChains/cosmosConditions"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/unifiedAccessControlConditions"
  to = "/coreConcepts/accessControl/conditionTypes/unifiedAccessControlConditions"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/booleanLogic"
  to = "/accessControl/conditionTypes/booleanLogic"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/updateableConditions"
  to = "/coreConcepts/accessControl/conditionTypes/updateableConditions"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/Ceramic/*"
  to = "/ToolsAndExamples/Integrations/Ceramic/intro"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/bundlrxarweave"
  to = "/ToolsAndExamples/Integrations/bundlrxarweave"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/additionalIntegrations"
  to = "/ToolsAndExamples/Integrations/additionalIntegrations"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/shareModal"
  to = "/ToolsAndExamples/Tools/shareModal"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/sdkexamples/dynamiccontent/"
  to = "/ToolsAndExamples/Tools/jwtverify"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/SDKExamples/examples"
  to = "/ToolsAndExamples/SDKExamples/dynamicContent"
  status = 302
  force = false

[[redirects]]
  from = "/litGrants"
  to = "/Ecosystem/litGrants"
  status = 302
  force = false

[[redirects]]
  from = "/Introduction/whatIsLitProtocol#join-the-community"
  to = "/Ecosystem/community"
  status = 302
  force = false

[[redirects]]
  from = "/faq"
  to = "/support/faq"
  status = 302
  force = false

[[redirects]]
  from = "/supportedChains"
  to = "/resources/supportedChains"
  status = 302
  force = false

[[redirects]]
  from = "/litactionsandpkps/whatarelitactionsandpkps/*"
  to = "/coreConcepts/LitActionsAndPKPs/intro"
  status = 302
  force = false

[[redirects]]
  from = "/accesscontrolconditions/*"
  to = "/coreConcepts/accessControl/intro"
  status = 302
  force = false

# 10/26/22 - dating for deprecation purposes
  
  [[redirects]]
  from = "/coreconcepts/litactionsandpkps/workingwithlitactions"
  to = "/SDK/Explanation/litActions"
  status = 302
  force = false

  [[redirects]]
  from = "/SDK/Explanation/EncryptionCategory/*"
  to = "/SDK/Explanation/encryption"
  status = 302
  force = false

# 01/12/23 - Lit Actions into it's own section
[[redirects]]
  from = "/SDK/Explanation/litActions"
  to = "/SDK/Explanation/LitActions/helloWorld"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/*"
  to = "/SDK/Explanation/encryption"
  status = 302
  force = false


# 02/14/23 - Move up Lit Actions sections from within SDK to the core concepts / programmatic signing section
[[redirects]]
  from = "/SDK/Explanation/LitActions/conditionalSigning/*"
  to = "/LitActions/workingWithActions/workingWithActions/conditionalSigning"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/Explanation/LitActions/usingFetch"
  to = "/LitActions/workingWithActions/usingFetch"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/Explanation/LitActions/authHelpers/*"
  to = "/LitActions/authHelpers"
  status = 302
  force = false

# 03/22/23 - docs re-org, flattening structure of docs

[[redirects]]
  from = "/Introduction/whatIsLitProtocol"
  to = "/whatIsLit"
  status = 301
  force = false

[[redirects]]
  from = "/Introduction/howItWorks"
  to = "/resources/howItWorks"
  status = 301
  force = false

# multiple bc redirects are case sensitive

[[redirects]]
  from = "/Introduction/stateOfNetwork"
  to = "/Support/stateOfNetwork"
  status = 301
  force = false

[[redirects]]
  from = "/introduction/stateofnetwork"
  to = "/Support/stateOfNetwork"
  status = 301
  force = false

[[redirects]]
  from = "/introduction/stateOfNetwork"
  to = "/Support/stateOfNetwork"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/usecases"
  to = "/useCases"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/accessControl/*"
  to = "/accessControl/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/LitActionsAndPKPs/intro"
  to = "/pkp/intro"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/LitActionsAndPKPs/PKPs"
  to = "/pkp/intro"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/LitActionsAndPKPs/actions/authHelpers"
  to = "/LitActions/authHelpers"
  status = 301
  force = false
  
[[redirects]]
  from = "/coreConcepts/LitActionsAndPKPs/actions/litActions"
  to = "/LitActions/intro"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/LitActionsAndPKPs/actions/conditionalSigning"
  to = "/LitActions/workingWithActions/conditionalSigning"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/LitActionsAndPKPs/actions/usingFetch"
  to = "/LitActions/workingWithActions/usingFetch"
  status = 301
  force = false

[[redirects]]
  from = "/coreConcepts/Wallets/*"
  to = "/pkp/wallets/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/SDK/Explanation/LitActions/usingEIP"
  to = "/LitActions/usingEIP"
  status = 301
  force = false

[[redirects]]
  from = "/SDK/Explanation/LitActions/logAndReturn"
  to = "/LitActions/workingWithActions/logAndReturn"
  status = 301
  force = false

[[redirects]]
  from = "/SDK/Explanation/LitActions/contracts"
  to = "/resources/contracts"
  status = 301
  force = false

[[redirects]]
  from = "/Support/glossary"
  to = "/resources/glossary"
  status = 301
  force = false

[[redirects]]
  from = "/LitActions/logAndReturn"
  to = "/LitActions/workingWithActions/logAndReturn"
  status = 301
  force = false

[[redirects]]
  from = "/LitActions/usingEIP"
  to = "/LitActions/additionalExamples/usingEIP"
  status = 301
  force = false

# 3/28 - continue adding support for links missing from initial pass
[[redirects]]
  from = "/support/supportedchains/"
  to = "/resources/supportedChains"
  status = 302
  force = false

[[redirects]]
  from = "/introduction/stateofnetwork"
  to = "/Support/stateOfNetwork"
  status = 301
  force = false

[[redirects]]
  from = "/introduction/stateofnetwork/*"
  to = "/Support/stateOfNetwork"
  status = 301
  force = false

[[redirects]]
  from = "/coreconcepts/litactionsandpkps/actions/*"
  to = "/LitActions/intro"
  status = 301
  force = false

[[redirects]]
  from = "/coreconcepts/wallets/intro/*"
  to = "/pkp/wallets/intro"
  status = 301
  force = false

[[redirects]]
  from = "/SDK/Explanation/WalletSigs/*"
  to = "/SDK/Explanation/authentication/*"
  status = 301
  force = false

[[redirects]]
  from = "/pkp/sendingTxs"
  to = "/pkp/usage"
  status = 301
  force = false