[[redirects]]
  from = "/docs/SDK/accessControlConditionExamples"
  to = "/docs/AccessControlConditions/evmBasicExamples"
  status = 302
  force = false

[[redirects]]
  from = "/docs/accessControlModal"
  to = "docs/ToolsAndExamples/shareModal"
  status = 302
  force = true

[[redirects]]
  from = "/docs/LitTools/shareModal"
  to = "/docs/ToolsAndExamples/shareModal"
  status = 302
  force = true

[[redirects]]
  from = "/docs/jwtVerifier"
  to = "/docs/ToolsAndExamples/additionalIntegrations#js-jwt-verifier"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/jwtVerifier"
  to = "/docs/ToolsAndExamples/additionalIntegrations#js-jwt-verifier"
  status = 302
  force = false

[[redirects]]
  from = "/docs/examples"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/examples"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/oauth"
  to = "/docs/ToolsAndExamples/additionalIntegrations#oauth-integrations"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/oauth"
  to = "/docs/ToolsAndExamples/additionalIntegrations#oauth-integrations"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ceramicIntegration"
  to = "/docs/ToolsAndExamples/Ceramic/intro"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/ceramicIntegration"
  to = "/docs/ToolsAndExamples/Ceramic/intro"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/intro"
  to = "/docs/SDK/intro"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/installation"
  to = "/docs/SDK/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/staticContent"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/SDKExamples/EncryptAndDecrypt/installation"
  to = "/docs/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/dynamicContent"
  to = "/docs/ToolsAndExamples/SDKExamples/dynamicContent"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/SDKExamples/dynamicContent"
  to = "/docs/ToolsAndExamples/SDKExamples/dynamicContent"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/authSig"
  to = "/docs/SDK/authSig"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/errorHandling"
  to = "/docs/SDK/errorHandling"
  status = 302
  force = false

[[redirects]]
  from = "/docs/LitTools/JSSDK/tests"
  to = "/docs/SDK/tests"
  status = 302
  force = false
  
[[redirects]]
from = "/docs/ExamplesAndGuides/examples"
to = "/docs/ExamplesAndGuides/SDKExamples/examples"
status = 302
force = false

[[redirects]]
  from = "/docs/whatislit/whatislitprotocol/"
  to = "/"
  status = 302
  force = false

[[redirects]]
  from = "/docs/WhatIsLit/howItWorks"
  to = "/docs/Introduction/howItWorks"
  status = 302
  force = false

[[redirects]]
  from = "/docs/intro"
  to = "/docs/Introduction/whatIsLitProtocol"
  status = 302
  force = false

[[redirects]]
  from = "/docs/AccessControlConditions/evmBasicExamples"
  to = "/docs/AccessControlConditions/EVM/basicExamples"
  status = 302
  force = false

[[redirects]]
  from = "/docs/AccessControlConditions/evmCustomContractCalls"
  to = "/docs/AccessControlConditions/EVM/customContractCalls"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/Ceramic/installation"
  to = "/docs/ToolsAndExamples/Ceramic/installation"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/Ceramic/encryption"
  to = "/docs/ToolsAndExamples/Ceramic/encryption"
  status = 302
  force = false

[[redirects]]
  from = "/docs/ExamplesAndGuides/Ceramic/decryption"
  to = "/docs/ToolsAndExamples/Ceramic/decryption"
  status = 302
  force = false

  [[redirects]]
  from = "/docs/ExamplesAndGuides/bundlrxarweave"
  to = "/docs/ToolsAndExamples/bundlrxarweave"
  status = 302
  force = false

# 7/21/22 - dating for deprecation purposes

[[redirects]]
  from = "/docs/Introduction/whatIsLitProtocol"
  to = "/"
  status = 302
  force = false

[[redirects]]
  from = "/docs/*"
  to = "/:splat"
  status = 302
  force = false

# 10/18/22 - docs re-org 1.5

[[redirects]]
  from = "/LitActionsAndPKPs/whatAreLitActionsAndPKPs"
  to = "/coreConcepts/LitActionsAndPKPs/intro"
  status = 302
  force = false

[[redirects]]
  from = "/LitActionsAndPKPs/workingWithLitActions"
  to = "/coreConcepts/LitActionsAndPKPs/workingWithLitActions"
  status = 302
  force = false

[[redirects]]
  from = "/LitActionsAndPKPs/toolsAndExamples"
  to = "/coreConcepts/LitActionsAndPKPs/toolsAndExamples"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/installation"
  to = "/SDK/Explanation/installation"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/authSig"
  to = "/SDK/Explanation/authSig"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/sessionKeys"
  to = "/SDK/Explanation/authSig"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/errorHandling"
  to = "/SDK/Explanation/tests"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/tests"
  to = "/SDK/Explanation/tests"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/intro"
  to = "/coreConcepts/accessControl/intro"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/EVM/basicExamples"
  to = "/coreConcepts/accessControl/EVM/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/EVM/*"
  to = "/coreConcepts/accessControl/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/solRpcConditions"
  to = "/coreConcepts/accessControl/otherChains/solRpcConditions"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/cosmosConditions"
  to = "/coreConcepts/accessControl/otherChains/cosmosConditions"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/unifiedAccessControlConditions"
  to = "/coreConcepts/accessControl/conditionTypes/unifiedAccessControlConditions"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/booleanLogic"
  to = "/coreConcepts/accessControl/conditionTypes/booleanLogic"
  status = 302
  force = false

[[redirects]]
  from = "/AccessControlConditions/updateableConditions"
  to = "/coreConcepts/accessControl/conditionTypes/updateableConditions"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/Ceramic/*"
  to = "/toolsAndExamples/integrations/Ceramic/intro"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/bundlrxarweave"
  to = "/toolsAndExamples/integrations/bundlrxarweave"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/additionalIntegrations"
  to = "/toolsAndExamples/integrations/additionalIntegrations"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/shareModal"
  to = "/toolsAndExamples/tools/shareModal"
  status = 302
  force = false

[[redirects]]
  from = "/toolsandexamples/sdkexamples/dynamiccontent/"
  to = "/toolsAndExamples/tools/jwtverify"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/SDKExamples/examples"
  to = "/toolsAndExamples/SDKExamples/dynamicContent"
  status = 302
  force = false

[[redirects]]
  from = "/litGrants"
  to = "/ecosystem/litGrants"
  status = 302
  force = false

[[redirects]]
  from = "/Introduction/whatIsLitProtocol#join-the-community"
  to = "/ecosystem/community"
  status = 302
  force = false

[[redirects]]
  from = "/faq"
  to = "/support/faq"
  status = 302
  force = false

[[redirects]]
  from = "/supportedChains"
  to = "/support/supportedChains"
  status = 302
  force = false

[[redirects]]
  from = "/litactionsandpkps/whatarelitactionsandpkps/*"
  to = "/coreConcepts/LitActionsAndPKPs/intro"
  status = 302
  force = false

[[redirects]]
  from = "/accesscontrolconditions/*"
  to = "/coreConcepts/accessControl/intro"
  status = 302
  force = false

# 10/26/22 - dating for deprecation purposes
  
  [[redirects]]
  from = "/coreconcepts/litactionsandpkps/workingwithlitactions"
  to = "/SDK/Explanation/litActions"
  status = 302
  force = false

  [[redirects]]
  from = "/SDK/Explanation/EncryptionCategory/*"
  to = "/SDK/Explanation/encryption"
  status = 302
  force = false

# 01/12/23 - Lit Actions into it's own section
[[redirects]]
  from = "/SDK/Explanation/litActions"
  to = "/SDK/Explanation/LitActions/helloWorld"
  status = 302
  force = false

[[redirects]]
  from = "/ToolsAndExamples/SDKExamples/EncryptAndDecrypt/*"
  to = "/SDK/Explanation/encryption"
  status = 302
  force = false


# 02/14/23 - Move up Lit Actions sections from within SDK to the core concepts / programmatic signing section
[[redirects]]
  from = "/SDK/Explanation/LitActions/conditionalSigning/*"
  to = "/coreConcepts/LitActionsAndPKPs/actions/conditionalSigning"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/Explanation/LitActions/usingFetch"
  to = "/coreConcepts/LitActionsAndPKPs/actions/usingFetch"
  status = 302
  force = false

[[redirects]]
  from = "/SDK/Explanation/LitActions/authHelpers/*"
  to = "/coreConcepts/LitActionsAndPKPs/actions/authHelpers"
  status = 302
  force = false
